begin;
create extension if not exists pgtap with schema extensions;
select plan(14);
select ok(not has_schema_privilege('authenticated','app_private','USAGE'),'Clients cannot access private ingestion state');
select ok(not has_table_privilege('authenticated','vault.decrypted_secrets','SELECT'),'Clients cannot decrypt bank tokens');
select ok(not has_function_privilege('anon','public.plaid_admin(text,jsonb)','EXECUTE'),'Anonymous callers cannot administer Items');
select ok(not has_function_privilege('authenticated','public.plaid_admin(text,jsonb)','EXECUTE'),'Authenticated callers cannot retrieve service tokens');
select ok(has_function_privilege('service_role','public.plaid_admin(text,jsonb)','EXECUTE'),'Trusted backend can administer Items');
select ok(not has_function_privilege('service_role','public.plaid_admin_internal(text,jsonb)','EXECUTE'),'Internal helpers cannot bypass the guarded entry point');
select ok(not has_function_privilege('anon','public.app_banking(integer)','EXECUTE'),'Connection reads require authentication');
select ok(has_function_privilege('authenticated','public.app_banking(integer)','EXECUTE'),'Owners can read safe banking projections');
select ok(not has_function_privilege('authenticated','public.app_bank_resolve_internal(uuid,integer,text,uuid,jsonb)','EXECUTE'),'Review version checks cannot be bypassed');
select ok(not has_function_privilege('authenticated','app_private.plaid_dispatch()','EXECUTE'),'Clients cannot mint signed worker dispatches');
select ok(not has_function_privilege('authenticated','public.plaid_worker_receipt(uuid)','EXECUTE'),'Clients cannot consume worker replay receipts');
select ok(not has_function_privilege('authenticated','public.plaid_schedule(text,text)','EXECUTE'),'Clients cannot replace scheduler secrets');
select set_config('request.jwt.claims','{"role":"service_role"}',true);
select is(public.plaid_worker_receipt('60000000-0000-4000-8000-000000000001'),true,'Fresh dispatch nonce is accepted');
select is(public.plaid_worker_receipt('60000000-0000-4000-8000-000000000001'),false,'Replayed dispatch nonce is rejected');
select * from finish();
rollback;
