project_id = "web-app"

[functions.plaid-create-link-token]
verify_jwt = true

[functions.plaid-import-transactions]
verify_jwt = true

[functions.plaid-transactions-webhook]
verify_jwt = false

[functions.plaid-disconnect-item]
verify_jwt = true

[functions.plaid-delete-disconnected-history]
verify_jwt = true

[functions.plaid-complete-item-update]
verify_jwt = true

[functions.plaid-retry-item-sync]
verify_jwt = true
